<a href="https://colab.research.google.com/github/jechavarria12/World_GDP_Neural_netowrk/blob/main/world_bank_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#Instalación de las librerías
!pip install -q pandas
!pip install -q numpy
!pip install -q scipy
!pip install -q matplotlib
!pip install -q seaborn
!pip install -q plotly
!pip install -q yellowbrick
!pip install -q scikit-learn
!pip install -q imbalanced-learn
!pip install -q tqdm
!pip install -q joblib
!pip install -q huggingface_hub
!pip install -q datasets
!pip install -q ydata_profiling

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [16]:
#Importar el dataset desde Kaggle
!kaggle datasets download sazidthe1/world-gdp-data
DATASET_NAME = 'world-gdp-data'

%cd {ROOT_DIR}
!unzip -o {DATASET_NAME}.zip -d {DATASET_NAME}

Dataset URL: https://www.kaggle.com/datasets/sazidthe1/world-gdp-data
License(s): Attribution 4.0 International (CC BY 4.0)
Downloading world-gdp-data.zip to /
100% 108k/108k [00:00<00:00, 537kB/s]
100% 108k/108k [00:00<00:00, 536kB/s]
/
Archive:  world-gdp-data.zip
  inflating: world-gdp-data/country_codes.csv
  inflating: world-gdp-data/gdp_data.csv

In [26]:
I#Usar pandas para tener los dos dataframes
import pandas as pd

df_1=pd.read_csv("world-gdp-data//country_codes.csv")
df_2=pd.read_csv('world-gdp-data//gdp_data.csv')

In [28]:
#Unir los Dataframes sobre la columna en común, country code
merged_df = pd.merge(df_1, df_2, on='country_code', how='inner')
print(merged_df.isna().sum())
merged_df.dropna(inplace=True)

country_code    0
region          0
income_group    0
country_name    0
year            0
value           0
dtype: int64

In [25]:

display(merged_df.head())

,country_code,region,income_group,country_name,year,value
0,ABW,Latin America & Caribbean,High income,Aruba,1986,405586592.2
1,ABW,Latin America & Caribbean,High income,Aruba,1987,487709497.2
2,ABW,Latin America & Caribbean,High income,Aruba,1988,596648044.7
3,ABW,Latin America & Caribbean,High income,Aruba,1989,695530726.3
4,ABW,Latin America & Caribbean,High income,Aruba,1990,764804469.3